name: flutter_data_stream_builder
description: A pragmatic StreamBuilder with sensible defaults
version: 0.0.1
homepage: https://github.com/flutterigniter/flutter_data_stream_builder

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter